// <auto-generated />
namespace Emarket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Update_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202005110517435_Update_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
